local ll = {}

function ll.load()
	local Race = require "game.raws.race"

	Race:new {
		name = "human",
		r = 0.85,
		g = 0.85,
		b = 0.85,
		icon = 'barbute.png',
	}
	Race:new {
		name = 'high beaver',
		r = 0.68,
		g = 0.4,
		b = 0.3,
		icon = 'beaver.png',
		description = 'high beavers',
		males_per_hundred_females = 108,
		child_age = 4,
		teen_age = 15,
		adult_age = 20,
		middle_age = 50,
		elder_age = 70,
		max_age = 100,
		minimum_comfortable_temperature = -5,
		minimum_absolute_temperature = -25,
		fecundity = 0.85,
		spotting = 0.5,
		visibility = 5,
		female_body_size = 1.5,
		female_worker_efficiency = 1,
		female_artisan_efficiency = 1,
		female_clerk_efficiency = 1,
		female_ruler_efficiency = 1,
		female_water_needs = 3,
		female_food_needs = 2,
		female_grains_needs = 2,
		female_fruit_needs = 2,
		female_meat_needs = 1,
		female_clothing_needs = 0.3,
		female_infrastructure_needs = 2,
		male_body_size = 2,
		male_worker_efficiency = 1,
		male_artisan_efficiency = 1,
		male_clerk_efficiency = 1,
		male_ruler_efficiency = 1,
		male_water_needs = 3,
		male_food_needs = 2,
		male_grains_needs = 2,
		male_fruit_needs = 2,
		male_meat_needs = 1,
		male_clothing_needs = 0.3,
		male_infrastructure_needs = 2,
		carrying_capacity_weight = 1.1,
		
		requires_large_river = true
	}
	Race:new {
		name = 'elf',
		r = 0.1,
		g = 0.5,
		b = 0.1,
		icon = 'woman-elf-face.png',
		description = 'elves',
		males_per_hundred_females = 100,
		child_age = 5,
		teen_age = 100,
		adult_age = 200,
		middle_age = 650,
		elder_age = 800,
		max_age = 1000,
		minimum_comfortable_temperature = -5,
		minimum_absolute_temperature = -15,
		fecundity = 0.5,
		spotting = 2,
		visibility = 0.25,
		female_body_size = 0.9,
		female_worker_efficiency = 2,
		female_artisan_efficiency = 2,
		female_clerk_efficiency = 2,
		female_ruler_efficiency = 2,
		female_water_needs = 1.2,
		female_food_needs = 1.2,
		female_grains_needs = 1,
		female_fruit_needs = 3,
		female_meat_needs = 1.3,
		female_clothing_needs = 1,
		female_infrastructure_needs = 5,
		male_body_size = 0.95,
		male_worker_efficiency = 2,
		male_artisan_efficiency = 2,
		male_clerk_efficiency = 2,
		male_ruler_efficiency = 2,
		male_water_needs = 1.2,
		male_food_needs = 1.2,
		male_grains_needs = 1,
		male_fruit_needs = 3,
		male_meat_needs = 1.3,
		male_clothing_needs = 1,
		male_infrastructure_needs = 5,
		carrying_capacity_weight = 2,

		requires_large_forest = true

	}
	Race:new {
		name = 'dwarf',
		r = 0.99,
		g = 0.106,
		b = 0.133,
		icon = 'dwarf.png',
		description = 'dwarf',
		males_per_hundred_females = 102,
		child_age = 4,
		teen_age = 30,
		adult_age = 50,
		middle_age = 150,
		elder_age = 250,
		max_age = 300,
		minimum_comfortable_temperature = -10,
		minimum_absolute_temperature = -25,
		minimum_comfortable_elevation = 800,
		fecundity = 0.75,
		spotting = 0.75,
		visibility = 0.75,
		female_body_size = 0.7,
		female_worker_efficiency = 1.5,
		female_artisan_efficiency = 1.5,
		female_clerk_efficiency = 1.5,
		female_ruler_efficiency = 1.5,
		female_water_needs = 1.2,
		female_food_needs = 1.2,
		female_grains_needs = 1.2,
		female_fruit_needs = 1.2,
		female_meat_needs = 1.2,
		female_clothing_needs = 1,
		female_infrastructure_needs = 3,
		male_body_size = 0.8,
		male_worker_efficiency = 1.5,
		male_artisan_efficiency = 1.5,
		male_clerk_efficiency = 1.5,
		male_ruler_efficiency = 1.5,
		male_water_needs = 1.2,
		male_food_needs = 1.2,
		male_grains_needs = 1.2,
		male_fruit_needs = 1.2,
		male_meat_needs = 1.1,
		male_clothing_needs = 1,
		male_infrastructure_needs = 3,
		carrying_capacity_weight = 1.5,

	}

	Race:new {
		name = 'Goblin',
		r = 0.1,
		g = 0.7,
		b = 0.1,
		icon = 'goblin.png',
		description = 'dwarf',
		males_per_hundred_females = 102,
		child_age = 1,
		teen_age = 5,
		adult_age = 10,
		middle_age = 20,
		elder_age = 40,
		max_age = 50,
		minimum_comfortable_temperature = 5,
		minimum_absolute_temperature = -10,
		fecundity = 4,
		spotting = 1.5,
		visibility = 0.5,
		female_body_size = 0.5,
		female_worker_efficiency = 0.6,
		female_artisan_efficiency = 0.6,
		female_clerk_efficiency = 0.6,
		female_ruler_efficiency = 0.6,
		female_water_needs = 0.25,
		female_food_needs = 0.25,
		female_grains_needs = 0.25,
		female_fruit_needs = 0.25,
		female_meat_needs = 0.25,
		female_clothing_needs = 0.25,
		female_infrastructure_needs = 0.25,
		male_body_size = 0.6,
		male_worker_efficiency = 0.6,
		male_artisan_efficiency = 0.6,
		male_clerk_efficiency = 0.6,
		male_ruler_efficiency = 0.6,
		male_water_needs = 0.25,
		male_food_needs = 0.25,
		male_grains_needs = 0.25,
		male_fruit_needs = 0.25,
		male_meat_needs = 0.25,
		male_clothing_needs = 0.25,
		male_infrastructure_needs = 0.25,
		carrying_capacity_weight = 0.25,

	}

end

return ll
